package com.task

const val SHARED_PREFERENCES_FILE_NAME = "witty_db"

const val LAST_CREDITCARD_KEY = "LAST_CREDITCARD"
const val CREDITCARD_EXP_MONTH_KEY = "CREDITCARD_EXP_MONTH_"
const val CREDITCARD_EXP_YEAR_KEY = "CREDITCARD_EXP_YEAR_"
const val CREDITCARD_CVV_KEY = "CREDITCARD_CVV_"
